### ISSUE TITLE
'parse' is not exported by ../node_modules/@agoric/babel-parser/lib/index.js

### ISSUE THREAD

**Issue by warner** [Agoric/playground-cosmos#4]
The `npm clean-install` works, but when I run `npm run build`, it fails with this error:

```
warner@agony:~/bindmounts/trees/playground-cosmos$ npm run build

> @agoric/playground-cosmos@0.0.1 build /home/warner/bindmounts/trees/playground-cosmos
> ./doRun.js build

cd cosmic-swingset && npm run build

> @agoric/cosmic-swingset@0.7.5-dev.0 prebuild /home/warner/bindmounts/trees/playground-cosmos/cosmic-swingset
> make all

GO111MODULE=on go build -v -buildmode=c-shared -o lib/libagcosmosdaemon.so lib/agcosmosdaemon.go
runtime/cgo
net
command-line-arguments
install_name_tool -id `pwd`/lib/libagcosmosdaemon.so lib/libagcosmosdaemon.so
/bin/sh: 1: install_name_tool: not found
Makefile:63: recipe for target 'compile-go' failed
make: [compile-go] Error 127 (ignored)
# Not needed, because we librarify ./cmd/ag-chain-cosmos as ./lib/libagcosmosdaemon.so
#GO111MODULE=on go install -tags " ledger" ./cmd/ag-chain-cosmos
GO111MODULE=on go install -v -tags " ledger" ./cmd/ag-cosmos-helper

> @agoric/cosmic-swingset@0.7.5-dev.0 build /home/warner/bindmounts/trees/playground-cosmos/cosmic-swingset
> node-gyp configure build

make: Entering directory '/home/warner/bindmounts/trees/playground-cosmos/cosmic-swingset/build'
  CC(target) Release/obj.target/nothing/../node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/agcosmosdaemon/lib/agcosmosdaemon-node.o
  SOLINK_MODULE(target) Release/obj.target/agcosmosdaemon.node
  COPY Release/agcosmosdaemon.node
make: Leaving directory '/home/warner/bindmounts/trees/playground-cosmos/cosmic-swingset/build'
cd evaluate && npm run build
cd SwingSet && npm run build
cd harden && npm run build
cd nat && npm run build

> @agoric/swingset-vat@0.0.17-dev.0 build /home/warner/bindmounts/trees/playground-cosmos/SwingSet
> npm run-script build-kernel


> @agoric/harden@0.0.4 build /home/warner/bindmounts/trees/playground-cosmos/harden
> rollup -c


> @agoric/evaluate@1.2.1-dev.0 build /home/warner/bindmounts/trees/playground-cosmos/evaluate
> exit 0


> @agoric/nat@2.0.1 build /home/warner/bindmounts/trees/playground-cosmos/nat
> rollup -c

cd default-evaluate-options && npm run build

src/index.js → dist/nat.umd.js, dist/nat.esm.js, dist/nat.cjs.js...

src/index.js → dist/harden.umd.js, dist/harden.esm.js, dist/harden.cjs.js...
created dist/nat.umd.js, dist/nat.esm.js, dist/nat.cjs.js in 25ms
cd SES && npm run build

> @agoric/default-evaluate-options@0.0.2 build /home/warner/bindmounts/trees/playground-cosmos/default-evaluate-options
> rollup -c


> @agoric/swingset-vat@0.0.17-dev.0 build-kernel /home/warner/bindmounts/trees/playground-cosmos/SwingSet
> node -r esm scripts/build-kernel.js

(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@agoric/make-hardener (imported by src/index.js)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
@agoric/make-hardener (guessing 'makeHardener')
created dist/harden.umd.js, dist/harden.esm.js, dist/harden.cjs.js in 261ms
cd make-hardener && npm run build

> ses@0.5.4-dev.0 build /home/warner/bindmounts/trees/playground-cosmos/SES
> git submodule update --init --recursive && node scripts/build-intermediate.js && rollup -c


src/index.js → dist/default-evaluate-options.umd.js, dist/default-evaluate-options.esm.js, dist/default-evaluate-options.cjs.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@agoric/transform-bang (imported by src/index.js)
@agoric/eventual-send (imported by src/index.js)
[!] Error: 'parse' is not exported by ../node_modules/@agoric/babel-parser/lib/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module-
src/index.js (1:9)
1: import { parse } from '@agoric/babel-parser';
            ^
2: import generate from '@babel/generator';
3: import makeBangTransformer from '@agoric/transform-bang';
Error: 'parse' is not exported by ../node_modules/@agoric/babel-parser/lib/index.js
    at error (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:9408:30)
    at Module.error (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:13347:9)
    at handleMissingExport (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:13269:21)
    at Module.traceVariable (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:13656:17)
    at ModuleScope.findVariable (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:12367:39)
    at Identifier$1.bind (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:8327:40)
    at CallExpression$1.bind (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:7952:31)
    at CallExpression$1.bind (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:10347:15)
    at SpreadElement.bind (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:7956:23)
    at SpreadElement.bind (/home/warner/bindmounts/trees/playground-cosmos/node_modules/rollup/dist/rollup.js:11745:15)

Submodule 'realms-shim' (https://github.com/Agoric/realms-shim.git) registered for path 'realms-shim'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @agoric/default-evaluate-options@0.0.2 build: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @agoric/default-evaluate-options@0.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Cloning into '/home/warner/bindmounts/trees/playground-cosmos/SES/realms-shim'...

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/warner/.npm/_logs/2019-07-26T18_36_38_337Z-debug.log
(node:20733) UnhandledPromiseRejectionWarning: @agoric/default-evaluate-options: invalid exit status 1
(node:20733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> @agoric/make-hardener@0.0.6 build /home/warner/bindmounts/trees/playground-cosmos/make-hardener
> rollup -c


src/index.js → dist/make-hardener.umd.js, dist/make-hardener.esm.js, dist/make-hardener.cjs.js...
created dist/make-hardener.umd.js, dist/make-hardener.esm.js, dist/make-hardener.cjs.js in 54ms
Submodule path 'realms-shim': checked out '45ec9d2d757825bd1ed245b992e0c57cb8f1d9fe'
wrote 69491 to src/stringifiedBundle
(node:20733) UnhandledPromiseRejectionWarning: @agoric/default-evaluate-options: invalid exit status 1
(node:20733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

src/index.js → dist/ses.esm.js, dist/ses.cjs.js...
created dist/ses.esm.js, dist/ses.cjs.js in 212ms

src/index.js → dist/ses.umd.js...
created dist/ses.umd.js in 173ms
```

It's not obvious to me which submodule was being worked on when it hit the babel problem, maybe `eventual-send`?

**Comment by michaelfig** [comment]
Ah yes, I forgot to automate this.  Extensive testing a few days ago revealed that `rollup` cannot run properly from the `node_modules` symlinks I set up by default.  So, I run it after a `clean-install` of `default-evaluate-options`.

**Comment by warner** [comment]
Great, `npm run build` works for me now. There's a warning about a circular dependency (all within `@babel/types`, but it doesn't seem to make the build fail. THanks!
